import { chromium } from '@playwright/test';
import fs from 'node:fs';
import assert from 'node:assert/strict';
fs.mkdirSync('artifacts', {recursive:true});
const browser = await chromium.launch({channel:'msedge',headless:true});
const context = await browser.newContext({viewport:{width:1440,height:1000}});
const page = await context.newPage();
const errors=[];
page.on('pageerror',e=>{ errors.push(e.message); console.error('BROWSER ERROR',e.message); });
const scores=Object.fromEntries(['Gameplay','Presentation','Narrative','Quality','Sound','Content','Pacing','Balance','UIUX','Impression'].map(k=>['score'+k,8]));
const records=[
 {id:1,ownerId:1,name:'Mass Effect Legendary Edition',type:'Full Release',location:'STEAM',finishDate:'2026-08-14',createDate:'2026-08-01',note:'A journey through the galaxy',replayValue:5,mainQuestDone:1,fav:1,replay:0,canceled:0,backlogItem:0,playtime:3600,...scores},
 {id:2,ownerId:1,name:'Outer Wilds',type:'Full Release',location:'STEAM',finishDate:'2025-12-20',createDate:'2025-12-01',note:'Explore the solar system',replayValue:3,mainQuestDone:1,fav:0,replay:0,canceled:0,backlogItem:0,playtime:1200,...scores},
 {id:3,ownerId:1,name:'Starfield',type:'Full Release',location:'STEAM',finishDate:'',createDate:'2026-08-01',note:'',replayValue:1,mainQuestDone:0,fav:0,replay:0,canceled:0,backlogItem:1,playtime:120,...scores}
];
const requests=[];
await page.route('https://api.ggdb.app/**',async route=>{
 const req=route.request(),action=new URL(req.url()).searchParams.get('action'); requests.push({action,method:req.method(),body:req.postData()});
 let body={success:true};
 if(action==='current-user') body={success:true,user:{username:'Explorer',isAdmin:true,playtimeEnabled:1}};
 if(action==='login') body={success:true,sessionId:'local-smoke-session',user:{isAdmin:true,playtimeEnabled:1}};
 if(action==='read') body=records;
 if(action==='igdb-suggestions') body=[{id:4,name:'Stellar Journey'}];
 if(action==='igdb-covers') body=[{id:4,url:'//images.igdb.com/igdb/image/upload/t_thumb/example.jpg',game_name:'Stellar Journey'}];
 if(action==='admin-logs') body=Array.from({length:26},(_,i)=>({timestamp:`2026-09-${String(i+1).padStart(2,'0')} 12:00:00`,user:'Explorer',action:'update',details:{name:'Mass Effect'}}));
 await route.fulfill({json:body});
});
await page.goto('http://127.0.0.1:4200/auth/login');
await page.waitForTimeout(900);
await page.screenshot({path:'artifacts/login-desktop.png',fullPage:true});
console.log('LOGIN', await page.locator('input').evaluateAll(xs=>xs.map(x=>({id:x.id,type:x.type,placeholder:x.placeholder}))));
await page.locator('input').filter({visible:true}).first().fill('Explorer');
await page.locator('input[type=password]').fill('local-example');
await page.getByRole('button',{name:'Sign In',exact:true}).click();
await page.waitForURL('http://127.0.0.1:4200/');
await page.waitForTimeout(700);
await page.screenshot({path:'artifacts/dashboard-desktop.png',fullPage:true});
await page.locator('.layout-topbar-menu').getByRole('button',{name:'Playthroughs'}).click();
await page.waitForTimeout(500);
await page.screenshot({path:'artifacts/overview-desktop.png',fullPage:true});
console.log('OVERVIEW',await page.locator('app-entry-card').count());
await page.getByRole('button',{name:'Table',exact:true}).click();
console.log('TABLE ROWS',await page.locator('.library-table tbody tr').count());
await page.getByRole('button',{name:'Timeline',exact:true}).click();
console.log('TIMELINE',await page.locator('.timeline-event').count());
await page.getByRole('button',{name:'Cards',exact:true}).click();
await page.getByPlaceholder('Search', {exact:true}).fill('Outer');
assert.equal(await page.locator('app-entry-card').count(),1);
await page.getByPlaceholder('Search', {exact:true}).fill('');
await page.locator('app-entry-card').first().click();
await page.waitForTimeout(400);
await page.screenshot({path:'artifacts/detail-desktop.png',fullPage:true});
console.log('DETAIL',await page.locator('input').evaluateAll(xs=>xs.map(x=>({id:x.id,type:x.type,disabled:x.disabled,value:x.value}))));
assert.equal(await page.locator('#finishDate').inputValue(),'14/08/2026');
await page.getByRole('button',{name:'Edit',exact:true}).click();
await page.locator('#note').fill('Material migration smoke check');
const slider=page.locator('app-rating input').first();
await slider.focus(); await slider.press('ArrowRight');
assert.equal(await slider.inputValue(),'9');
await page.locator('app-fieldset').filter({has:page.locator('legend').getByText('Gameplay',{exact:true})}).getByRole('switch').click();
assert.equal(await slider.isDisabled(),true);
await page.getByRole('button',{name:'Cover',exact:true}).click();
await page.getByRole('dialog').waitFor();
assert.match(await page.getByRole('dialog').innerText(),/Stellar Journey/);
await page.getByRole('dialog').getByText('Stellar Journey',{exact:true}).click();
await page.getByRole('dialog').waitFor({state:'hidden'});
await page.getByRole('button',{name:'Delete',exact:true}).click();
await page.getByRole('dialog').getByRole('button',{name:'Cancel',exact:true}).click();
assert.equal(requests.some(r=>r.action==='delete'),false);
await page.getByRole('button',{name:'Save Changes',exact:true}).click();
await page.waitForURL(url=>url.pathname === '/overview');
const saved=JSON.parse(requests.findLast(r=>r.action==='update').body);
assert.equal(saved.note,'Material migration smoke check');
assert.equal(saved.scoreGameplay,0);
assert.equal(saved.scorePresentation,8);
assert.equal(saved.finishDate,'2026-08-14');
assert.equal(saved.cover,'https://images.igdb.com/igdb/image/upload/t_cover_big/example.jpg');
console.log('EDIT: score, disabled category, cover, deletion cancellation and save payload passed');
await page.locator('.layout-topbar-menu').getByRole('button',{name:'Profile',exact:true}).click();
await page.waitForTimeout(300);
await page.locator('app-profile mat-slide-toggle').nth(1).getByRole('switch').click();
assert.equal(await page.evaluate(()=>localStorage.getItem('rpgRarityEnabled')),'true');
await page.locator('app-profile-configurator').getByTitle('Violet',{exact:true}).click();
assert.equal(await page.evaluate(()=>localStorage.getItem('primaryColor')),'violet');
await page.locator('app-profile app-select mat-select').click();
await page.getByRole('option',{name:'Deutsch',exact:true}).click();
await page.getByText('Sprache',{exact:true}).waitFor();
assert.equal(await page.evaluate(()=>localStorage.getItem('language')),'de');
await page.locator('app-profile app-select mat-select').click();
await page.getByRole('option',{name:'English',exact:true}).click();
await page.screenshot({path:'artifacts/profile-desktop.png',fullPage:true});
await page.locator('.layout-topbar-menu').getByRole('button',{name:'Control',exact:true}).click();
await page.locator('mat-paginator').waitFor();
assert.equal(await page.locator('tr.mat-mdc-row').count(),10);
await page.getByRole('button',{name:'Next page',exact:true}).click();
await page.locator('tr.mat-mdc-row').first().getByRole('button',{name:'Details'}).click();
await page.getByRole('dialog').waitFor();
await page.keyboard.press('Escape');
await page.getByRole('dialog').waitFor({state:'hidden'});
await page.locator('.layout-topbar-menu').getByRole('button',{name:'Backlog',exact:true}).click();
await page.getByText('Starfield',{exact:true}).click();
await page.getByRole('button',{name:'Game finished!',exact:true}).click();
assert.equal(await page.locator('app-rating').count(),10);
assert.equal(await page.locator('#finishDate').isDisabled(),false);
await page.locator('.layout-topbar-menu').getByRole('button',{name:'Profile',exact:true}).click();
await page.setViewportSize({width:390,height:844});
await page.waitForTimeout(700);
await page.screenshot({path:'artifacts/profile-mobile.png',fullPage:true});
console.log('MOBILE',await page.locator('.layout-main').evaluate(e=>({width:e.clientWidth,scrollWidth:e.scrollWidth,top:e.getBoundingClientRect().top})));
console.log('ERRORS',JSON.stringify(errors));
console.log('ACTIONS',JSON.stringify(requests.map(r=>r.action)));
await browser.close();
if(errors.length) process.exitCode=1;
